# Generated by Django 4.2 on 2023-04-07 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emp_data", "0002_register"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Register",
        ),
    ]
