# Generated by Django 4.2 on 2023-04-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emp_data", "0003_delete_register"),
    ]

    operations = [
        migrations.CreateModel(
            name="Register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("e_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=20)),
                ("username", models.CharField(max_length=20)),
                ("designation", models.CharField(max_length=20)),
                ("password1", models.CharField(max_length=15)),
                ("password2", models.CharField(max_length=15)),
            ],
        ),
    ]
